name: release

on:
  push:
    branches:
      - main
jobs:
  goreleaser:
    if: github.repository == 'funstory-ai/gobun'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload gobin
        uses: actions/upload-artifact@v4
        with:
          name: gobin_${{ github.sha }}
          retention-days: 1
          path: |
            dist/gobun_linux_amd64_v1/gobun
            dist/gobun_darwin_all/gobun
          if-no-files-found: error