name: release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - main
      - develop
jobs:
  goreleaser:
    if: github.repository == 'funstory-ai/gobun'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload gobin
        uses: actions/upload-artifact@v4
        with:
          name: gobin_${{ github.sha }}
          retention-days: 1
          path: |
            dist/gobun_linux_amd64_v1/gobun
            dist/gobun_linux_arm64_v8.0/gobun
            dist/gobun_darwin_arm64_v8.0/gobun
            dist/gobun_darwin_amd64_v1/gobun
          if-no-files-found: error
      - name: Prepare Release Files
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p release
          # Linux AMD64
          cp dist/gobun_linux_amd64_v1/gobun release/gobun-linux-amd64
          tar -czf release/gobun-linux-amd64.tar.gz -C release gobun-linux-amd64
          # Linux ARM64
          cp dist/gobun_linux_arm64_v8.0/gobun release/gobun-linux-arm64
          tar -czf release/gobun-linux-arm64.tar.gz -C release gobun-linux-arm64
          # Darwin (macOS) ARM64
          cp dist/gobun_darwin_arm64_v8.0/gobun release/gobun-darwin-arm64
          tar -czf release/gobun-darwin-arm64.tar.gz -C release gobun-darwin-arm64
          # Darwin (macOS) AMD64
          cp dist/gobun_darwin_amd64_v1/gobun release/gobun-darwin-amd64
          tar -czf release/gobun-darwin-amd64.tar.gz -C release gobun-darwin-amd64
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/*.tar.gz